version: '3.7'

services:
  web:
    restart: always
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: /bin/bash -c 'sleep 7; python3 manage.py runserver 0.0.0.0:8000'
  db:
    restart: always
    image: postgres:11.5-alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres-data: