version: '3.7'

services:
  web:
    restart: always
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: >
      bash -c "cd /usr/src/app/ &&
      chmod +x wait-for-postgres.sh &&
      ./wait-for-postgres.sh db:5432 &&
      python3 manage.py collectstatic --noinput &&
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py ensure_adminuser --username=admin --email=admin@example.com --password=admin &&
      python3 manage.py runserver 0.0.0.0:8000"
    container_name: django_web
  db:
    restart: always
    image: postgres:11.5-alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    container_name: django_db

volumes:
  postgres-data: